# .github/dependabot.yml
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the root directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Automatically assign reviewers if needed (optional)
    # reviewers:
    #   - "your-github-username"
    # Automatically assign labels (optional)
    # labels:
    #   - "dependencies"
    #   - "npm"